name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:lts

    steps:
      - name: Check for updates
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@latest-8 --activate

      - name: Set pnpm store directory
        run: pnpm config set store-dir .pnpm-store

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: dist
                
